name: track_workouts
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  chopper: ^3.0.3
  angel_serialize: ^2.2.3+3
  data_connection_checker: ^0.3.4
  dartz: ^0.9.1
  uuid: ^2.2.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.3
  build_runner:
  angel_serialize_generator: ^2.5.0
  intl: ^0.16.1
  easy_rich_text: ^0.5.1
  auto_size_text: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima-Regular.otf
        - asset: assets/fonts/Proxima-Bold.otf
          weight: 700