name: track_workouts
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima-Regular.otf
        - asset: assets/fonts/Proxima-Bold.otf
          weight: 700